<a href="https://colab.research.google.com/github/EdmarBortoletto/Ciencias-de-Dados/blob/main/Kernel_PCA_Saude_Fetal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
base_fetal = pd.read_csv('fetal_health.csv')
base_fetal

baseline value  accelerations  fetal_movement  uterine_contractions  \
0              120.0          0.000           0.000                 0.000   
1              132.0          0.006           0.000                 0.006   
2              133.0          0.003           0.000                 0.008   
3              134.0          0.003           0.000                 0.008   
4              132.0          0.007           0.000                 0.008   
...              ...            ...             ...                   ...   
2121           140.0          0.000           0.000                 0.007   
2122           140.0          0.001           0.000                 0.007   
2123           140.0          0.001           0.000                 0.007   
2124           140.0          0.001           0.000                 0.006   
2125           142.0          0.002           0.002                 0.008   

      light_decelerations  severe_decelerations  prolongued_decelerations  \
0                   0.000                   0.0                       0.0   
1                   0.003                   0.0                       0.0   
2                   0.003                   0.0                       0.0   
3                   0.003                   0.0                       0.0   
4                   0.000                   0.0                       0.0   
...                   ...                   ...                       ...   
2121                0.000                   0.0                       0.0   
2122                0.000                   0.0                       0.0   
2123                0.000                   0.0                       0.0   
2124                0.000                   0.0                       0.0   
2125                0.000                   0.0                       0.0   

      abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                                73.0                                   0.5   
1                                17.0                                   2.1   
2                                16.0                                   2.1   
3                                16.0                                   2.4   
4                                16.0                                   2.4   
...                               ...                                   ...   
2121                             79.0                                   0.2   
2122                             78.0                                   0.4   
2123                             79.0                                   0.4   
2124                             78.0                                   0.4   
2125                             74.0                                   0.4   

      percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                                  43.0       ...   
1                                                   0.0       ...   
2                                                   0.0       ...   
3                                                   0.0       ...   
4                                                   0.0       ...   
...                                                 ...       ...   
2121                                               25.0       ...   
2122                                               22.0       ...   
2123                                               20.0       ...   
2124                                               27.0       ...   
2125                                               36.0       ...   

      histogram_min  histogram_max  histogram_number_of_peaks  \
0              62.0          126.0                        2.0   
1              68.0          198.0                        6.0   
2              68.0          198.0                        5.0   
3              53.0          170.0                       11.0   
4              53.0          170.0                   

In [ ]:
X_fetal = base_fetal.iloc[:, 0:21].values
X_fetal

array([[1.20e+02, 0.00e+00, 0.00e+00, ..., 1.21e+02, 7.30e+01, 1.00e+00],
       [1.32e+02, 6.00e-03, 0.00e+00, ..., 1.40e+02, 1.20e+01, 0.00e+00],
       [1.33e+02, 3.00e-03, 0.00e+00, ..., 1.38e+02, 1.30e+01, 0.00e+00],
       ...,
       [1.40e+02, 1.00e-03, 0.00e+00, ..., 1.52e+02, 4.00e+00, 1.00e+00],
       [1.40e+02, 1.00e-03, 0.00e+00, ..., 1.51e+02, 4.00e+00, 1.00e+00],
       [1.42e+02, 2.00e-03, 2.00e-03, ..., 1.45e+02, 1.00e+00, 0.00e+00]])

In [ ]:
y_fetal = base_fetal.iloc[:,21].values
y_fetal

array([2., 1., 1., ..., 2., 2., 1.])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler_fetal = StandardScaler()
X_fetal = scaler_fetal.fit_transform(X_fetal)

In [ ]:
X_fetal

array([[-1.35222005, -0.8223883 , -0.20320955, ..., -1.18164215,
         1.87056871,  1.11298001],
       [-0.1325256 ,  0.73013282, -0.20320955, ...,  0.13203796,
        -0.23499819, -0.52452553],
       [-0.03088439, -0.04612774, -0.20320955, ..., -0.00624416,
        -0.2004807 , -0.52452553],
       ...,
       [ 0.68060404, -0.56363478, -0.20320955, ...,  0.96173066,
        -0.51113811,  1.11298001],
       [ 0.68060404, -0.56363478, -0.20320955, ...,  0.8925896 ,
        -0.51113811,  1.11298001],
       [ 0.88388645, -0.30488126, -0.16034157, ...,  0.47774325,
        -0.61469058, -0.52452553]])

In [ ]:
from sklearn.model_selection import train_test_split
X_fetal_treinamento, X_fetal_teste, y_fetal_treinamento, y_fetal_teste = train_test_split(X_fetal,y_fetal,test_size=0.15)

In [ ]:
X_fetal_treinamento.shape, X_fetal_teste.shape

((1807, 21), (319, 21))

In [ ]:
from sklearn.decomposition import KernelPCA

In [ ]:
kpca = KernelPCA(n_components=8, kernel='rbf')
X_fetal_treinamento_kpca = kpca.fit_transform(X_fetal_treinamento)
X_fetal_teste_kpca = kpca.transform(X_fetal_teste)

In [ ]:
X_fetal_treinamento_kpca.shape,X_fetal_teste_kpca.shape

((1807, 8), (319, 8))

In [ ]:
X_fetal_treinamento_kpca

array([[ 0.57384287,  0.00429938, -0.01836522, ...,  0.04928269,
         0.20741874, -0.20449836],
       [ 0.65232063, -0.10515908,  0.2089031 , ...,  0.07003567,
         0.16826574,  0.06475088],
       [ 0.53389031,  0.11705828, -0.16049586, ...,  0.115405  ,
         0.06977618,  0.00596051],
       ...,
       [-0.15275687,  0.54140607, -0.1786287 , ..., -0.19265335,
         0.0555581 ,  0.10022328],
       [-0.03671015,  0.37135871, -0.32954561, ...,  0.07785426,
        -0.0877776 ,  0.14441861],
       [ 0.4808654 ,  0.08732464, -0.21989453, ...,  0.01607027,
         0.16874346, -0.11260231]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
random_forest_fetal_kpca = RandomForestClassifier(n_estimators = 40, random_state=0, criterion = 'entropy')
random_forest_fetal_kpca.fit(X_fetal_treinamento_kpca, y_fetal_treinamento)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [ ]:
previsoes_2 = random_forest_fetal_kpca.predict(X_fetal_teste_kpca)
previsoes_2

array([1., 3., 1., 2., 3., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 2., 1., 3., 1., 1., 1., 1., 1., 2., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 2., 1., 1., 2., 1., 2., 1., 2., 1., 2., 1., 1., 1.,
       2., 1., 1., 1., 2., 1., 1., 1., 3., 3., 3., 1., 1., 1., 1., 1., 1.,
       3., 1., 1., 1., 1., 3., 1., 2., 1., 3., 1., 1., 1., 1., 1., 3., 1.,
       1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1.,
       1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 2., 2., 1., 1., 3., 1.,
       1., 1., 1., 2., 1., 2., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 3., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [ ]:
y_fetal_teste

array([1., 3., 1., 2., 3., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1.,
       2., 1., 1., 2., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1.,
       1., 1., 1., 1., 2., 2., 1., 2., 2., 3., 1., 1., 1., 1., 1., 2., 1.,
       1., 1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 1., 1., 1., 3., 1., 1.,
       1., 1., 1., 1., 2., 1., 1., 2., 1., 1., 1., 2., 1., 2., 2., 1., 1.,
       2., 1., 1., 2., 3., 1., 1., 1., 3., 3., 1., 1., 1., 1., 1., 1., 1.,
       3., 1., 1., 1., 1., 3., 1., 2., 3., 3., 1., 1., 1., 1., 1., 2., 1.,
       1., 2., 1., 1., 3., 1., 1., 1., 1., 1., 1., 3., 1., 1., 2., 1., 2.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 3., 1., 1.,
       1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 2., 2., 1., 1., 3., 1.,
       1., 1., 1., 2., 1., 2., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 2., 1., 1., 1., 1., 3., 1., 1., 3., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [ ]:
y_fetal_treinamento.shape
X_fetal_treinamento_kpca.shape

(1807, 8)

In [ ]:
previsoes_2.shape

(319,)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_fetal_teste.astype(str), previsoes_2.astype(str))

0.9028213166144201