<a href="https://colab.research.google.com/github/EdmarBortoletto/Ciencias-de-Dados/blob/main/Rede_Neural_Spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Rede Neural aplicação
## Alunos: Edmar e Robson


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder #Transformar classes em numeros
from sklearn.feature_extraction.text import CountVectorizer #Cria Vetor com o texto
from sklearn.metrics import confusion_matrix
from keras.models import Sequential # Conjunto de camadas sequenciais
from keras.layers import Dense, Dropout
from google.colab import files


In [ ]:
# upload do arquivo
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv


In [ ]:
# Lê o arquivo CSV
df = pd.read_csv('spam.csv', encoding='ISO-8859-1')  # Use a codificação adequada

# Remove colunas que começam com 'Unnamed'
df = df.loc[:, ~df.columns.str.startswith('Unnamed')]

# Visualiza as primeiras linhas do DataFrame modificado
print(df.head())


     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...


In [ ]:
df.rename(columns={'v1': 'category', 'v2': 'message'}, inplace=True)


In [ ]:

df.head()

category                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(df['category'])
print(y)

[0 0 1 ... 0 0 0]


Divisão dos dados entre treino e teste

In [ ]:
mensagens = df['message'].values
X_train, X_test, y_train, y_test = train_test_split(mensagens, y, test_size=0.3)
print(X_train)

["I'm leaving my house now."
 'Lol. Well quality aint bad at all so i aint complaining'
 "Please don't text me anymore. I have nothing else to say." ...
 'Aslamalaikkum....insha allah tohar beeen muht albi mufti mahfuuz...meaning same here....'
 'Pls send me the correct name da.' 'See the forwarding message for proof']


In [ ]:
vetorizador = CountVectorizer()# Cria vetor de 0 e 1 para cada palavra (OneHot Encoding)
vetorizador.fit(X_train)#Fit cria o modelo
X_train = vetorizador.transform(X_train)
X_test = vetorizador.transform(X_test)
print(X_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Visualizar vetor X_train

In [ ]:
import numpy as np
np.set_printoptions(threshold=np.inf)

In [ ]:
X_train.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
print(X_train.shape[1])

7257


In [ ]:
modelo = Sequential() #adicionar as camadas
#Camada de entrada
# units: neuronios; activation; funcao de ativação; input_dim: qtdade de colunas
modelo.add(Dense(units=10, activation='relu',input_dim=X_train.shape[1]))
#Tecnica para minimizar overfit
#Remove aleatoriamente 1% de sinapses (conexoes)
modelo.add(Dropout(0.1))
#2º camada oculta densa
#nº de neuronios ser referente ao numero de classes
modelo.add(Dense(units=8, activation='relu'))
modelo.add(Dropout(0.1))
#Ultima camada
#Como vai retornar somente 1 valor, units = 1; Muda função de ativação
modelo.add(Dense(units=1, activation='sigmoid'))

In [ ]:
#Compliar a rede
#Função loss: função de perda
#optmizer: Juste dos pesos. "adam": estocástico
#metrics: Avaliar performance
modelo.compile(loss="mean_squared_error", optimizer="adam", metrics=['accuracy'])
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                72580     
                                                                 
 dropout (Dropout)           (None, 10)                0         
                                                                 
 dense_1 (Dense)             (None, 8)                 88        
                                                                 
 dropout_1 (Dropout)         (None, 8)                 0         
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 72677 (283.89 KB)
Trainable params: 72677 (283.89 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
#Dados de treino
#epochs: serão passados todos os dados de treinos pela rede
#batch_size: A cada qtos registros atualiza-se a rede?
#verbose: retorno do processo iterativo de treinamento
#validation_data: treina e usa dados de validação para melhorar o modelo

modelo.fit(X_train, y_train, epochs=20, batch_size=10, verbose = True, validation_data=(X_test, y_test))

Epoch 1/20
390/390 [==============================] - 4s 5ms/step - loss: 0.0967 - accuracy: 0.9162 - val_loss: 0.0194 - val_accuracy: 0.9821
Epoch 2/20
390/390 [==============================] - 1s 4ms/step - loss: 0.0137 - accuracy: 0.9887 - val_loss: 0.0121 - val_accuracy: 0.9844
Epoch 3/20
390/390 [==============================] - 2s 6ms/step - loss: 0.0072 - accuracy: 0.9938 - val_loss: 0.0111 - val_accuracy: 0.9856
Epoch 4/20
390/390 [==============================] - 3s 8ms/step - loss: 0.0045 - accuracy: 0.9956 - val_loss: 0.0103 - val_accuracy: 0.9874
Epoch 5/20
390/390 [==============================] - 3s 7ms/step - loss: 0.0028 - accuracy: 0.9977 - val_loss: 0.0105 - val_accuracy: 0.9874
Epoch 6/20
390/390 [==============================] - 2s 4ms/step - loss: 0.0026 - accuracy: 0.9977 - val_loss: 0.0097 - val_accuracy: 0.9892
Epoch 7/20
390/390 [==============================] - 1s 4ms/step - loss: 0.0013 - accuracy: 0.9990 - val_loss: 0.0097 - val_accuracy: 0.9898
Epoch 

Métricas

In [ ]:
from keras.src.metrics import accuracy
loss, accuracy = modelo.evaluate(X_test, y_test)
print("loss: ", loss)
print("Acurácia: ", accuracy)

53/53 [==============================] - 0s 3ms/step - loss: 0.0102 - accuracy: 0.9880
loss:  0.010178896598517895
Acurácia:  0.9880383014678955


In [ ]:
nova_previsao = modelo.predict(X_test)
nova_previsao

In [ ]:
prev = (nova_previsao > 0.5)
prev

array([[False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [ ]:
cm = confusion_matrix(y_test, prev)
cm

array([[1434,    5],
       [  15,  218]])

## Rede Neural 2 - Deep Learning


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder #Transformar classes em numeros
from sklearn.feature_extraction.text import CountVectorizer #Cria Vetor com o texto
from sklearn.metrics import confusion_matrix
from keras.models import Sequential # Conjunto de camadas sequenciais
from keras.layers import Dense, Dropout, Flatten, Embedding
from google.colab import files

In [ ]:
!pip install keras_preprocessing

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 1.3 MB/s eta 0:00:00


In [ ]:
from keras.preprocessing.text import Tokenizer
from keras_preprocessing.sequence import pad_sequences

Transformaçao do texto em dados tabulares

In [ ]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(df['category'])
print(y)

In [ ]:
mensagens = df['message'].values
X_train, X_test, y_train, y_test = train_test_split(mensagens, y, test_size=0.3)

In [ ]:
# 1 - Tokenizar o texto
token = Tokenizer(num_words = 1000)#nº max de palavras a serem mantidas
#Fit: transforma
token.fit_on_texts(X_train)
#Criação da matriz densa dos tokens
X_train = token.texts_to_sequences(X_train)
X_test = token.texts_to_sequences(X_test)

In [ ]:
#Matriz densa dos token
#Transformou palavras em numeros
print(X_train)

[[835, 239, 10, 142, 27, 26], [183, 918, 24, 85, 577, 191, 1, 27, 197, 14, 4, 288, 23, 25, 21, 136, 7, 27, 267, 98, 127, 183, 124, 8, 85, 66], [39, 8, 5, 388, 61, 40, 17, 485, 2, 215, 6, 6, 17, 192, 5, 160, 2, 134, 37, 15, 719, 198, 289, 77, 240], [22, 3, 2, 52, 12, 256], [94, 720, 2, 187, 230, 765, 15, 7, 549], [404, 78, 145, 171, 5, 389, 8, 97, 218], [32, 50, 61, 158, 1, 60, 143], [50, 27, 40, 26, 9, 5, 405], [323, 50, 61, 3, 95, 3, 29, 33, 103], [54, 578, 48, 442, 3, 62, 113, 836, 60, 13, 137, 1, 95, 16, 3, 7, 70, 11, 67, 5, 919, 2, 145, 3, 296, 7, 129], [3, 17, 192, 4, 290, 424, 165, 30, 4, 579, 160, 2, 134, 671, 160, 15, 82, 230, 199, 920, 18, 390, 314, 550], [109, 6, 18, 5, 5, 57, 18, 7, 580, 2, 42, 41], [1, 200, 344, 7, 49, 55, 161, 406, 7, 36, 49, 118], [132, 180, 84, 1, 315, 33, 29, 60, 7, 14, 672, 71, 766, 71, 50, 14, 8, 24, 71, 767, 52, 80, 602, 4, 7, 71, 443, 14, 27, 314, 42, 41, 1, 96, 56, 35, 14, 324, 28, 2, 172, 219, 66, 40, 96, 17, 113, 603, 721, 32, 49, 144, 19, 208, 1

In [ ]:
#Garantir que todos os tokens tenham a mesma quantidade de elementos numericos
#Preenche com zeros depois do final da numeração
# Tamanho maximo: 500 caracteres
X_train = pad_sequences(X_train, padding="post", maxlen=500)
X_test = pad_sequences(X_test, padding="post", maxlen=500)

In [ ]:
# Dados em forma tabular
print(X_train)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
print(len(token.word_index))

7455


In [ ]:
modelo = Sequential()
#Camada Embedding?
#input_dim: tamanho vocabulario
#Output_dim: tamanho do vetor denso
#input_length: comprimento da sequencia
modelo.add(Embedding(input_dim=len(token.word_index), output_dim=50, input_length=500))
modelo.add(Flatten())#Conecta camada Embedding com camada densa

modelo.add(Dense(units=10, activation="relu"))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=1, activation="sigmoid"))

In [ ]:
modelo.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])
modelo.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 500, 50)           372750    
                                                                 
 flatten (Flatten)           (None, 25000)             0         
                                                                 
 dense_3 (Dense)             (None, 10)                250010    
                                                                 
 dropout_2 (Dropout)         (None, 10)                0         
                                                                 
 dense_4 (Dense)             (None, 1)                 11        
                                                                 
Total params: 622771 (2.38 MB)
Trainable params: 622771 (2.38 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
modelo.fit(X_train, y_train, epochs=20, batch_size=10,verbose=True, validation_data=(X_test,y_test))

Epoch 1/20
390/390 [==============================] - 9s 20ms/step - loss: 0.0650 - accuracy: 0.9328 - val_loss: 0.0360 - val_accuracy: 0.9815
Epoch 2/20
390/390 [==============================] - 6s 16ms/step - loss: 0.0328 - accuracy: 0.9867 - val_loss: 0.0283 - val_accuracy: 0.9862
Epoch 3/20
390/390 [==============================] - 5s 12ms/step - loss: 0.0240 - accuracy: 0.9921 - val_loss: 0.0235 - val_accuracy: 0.9856
Epoch 4/20
390/390 [==============================] - 4s 11ms/step - loss: 0.0179 - accuracy: 0.9944 - val_loss: 0.0200 - val_accuracy: 0.9868
Epoch 5/20
390/390 [==============================] - 7s 18ms/step - loss: 0.0131 - accuracy: 0.9964 - val_loss: 0.0182 - val_accuracy: 0.9874
Epoch 6/20
390/390 [==============================] - 4s 11ms/step - loss: 0.0101 - accuracy: 0.9977 - val_loss: 0.0159 - val_accuracy: 0.9880
Epoch 7/20
390/390 [==============================] - 4s 11ms/step - loss: 0.0083 - accuracy: 0.9972 - val_loss: 0.0162 - val_accuracy: 0.9844

In [ ]:
from keras.src.metrics import accuracy
loss, accuracy = modelo.evaluate(X_test, y_test)
print("loss: ", loss)
print("Acurácia: ", accuracy)

53/53 [==============================] - 0s 3ms/step - loss: 0.0128 - accuracy: 0.9868
loss:  0.012793252244591713
Acurácia:  0.9868420958518982


In [ ]:
nova_previsao = modelo.predict(X_test)
nova_previsao

53/53 [==============================] - 0s 3ms/step


array([[9.97779429e-01],
       [1.08986123e-18],
       [1.53661958e-14],
       [1.17484442e-05],
       [4.74594582e-12],
       [9.69824468e-17],
       [5.04572953e-14],
       [3.55067436e-06],
       [1.21765340e-16],
       [1.60185664e-05],
       [1.72557038e-10],
       [2.67017332e-15],
       [1.11465766e-07],
       [9.99626219e-01],
       [1.37574530e-09],
       [9.97919559e-01],
       [5.29454813e-11],
       [7.06174745e-08],
       [1.37772819e-04],
       [9.98746455e-01],
       [2.60949315e-15],
       [9.99421954e-01],
       [3.89531493e-17],
       [9.98695254e-01],
       [9.99960959e-01],
       [6.14246720e-17],
       [1.53045464e-13],
       [3.65060121e-14],
       [5.42095535e-10],
       [4.07029597e-25],
       [1.72126846e-07],
       [6.31904728e-12],
       [1.47360884e-15],
       [5.13092004e-14],
       [1.15326607e-21],
       [2.94156843e-12],
       [8.32745504e-12],
       [2.75951467e-11],
       [7.44148233e-12],
       [2.75232246e-12],


In [ ]:
prev = (nova_previsao > 0.5)
prev

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [ ]:
cm = confusion_matrix(y_test, prev)
cm

array([[1461,    2],
       [  20,  189]])